// Package trace provides the global trace ID (trace_id) spanning a whole
// request-response chain.
//
// The caller injects a trace_id at the entry point (HTTP handler / service
// method) via WithTraceID; every downstream consumer (SOAP client, logging)
// then reads the same ID from the context, tying one complete request
// together across logs, SOAP request-body attributes and HTTP headers.
//
// Propagation follows W3C Trace Context / OpenTelemetry boundary semantics:
// the trace_id preferably arrives via the X-Trace-Id HTTP header from the
// caller; when absent this service generates one (NewID). This service only
// back-fills trace_id into the request body when its TraceId business
// attribute is empty (see BaseCoreReq.InjectInfrastructure) and never
// overwrites a caller-provided business value. Travelport's upstream
// TransactionId is generated by the upstream itself and appears only in
// responses; it is not propagated through this service's context, and
// callers simply read it from the response JSON's transactionId field.
package trace

import (
	"context"
	"crypto/rand"
	"fmt"
)

type ctxKey string

const traceIDKey ctxKey = "trace_id"

// NewID generates a random trace ID in UUID v4 display form (e.g.
// 60e47d21-e9f0-4138-9163-099114dd85e3), without the TP- prefix. The value
// is used for the HTTP X-Trace-Id header and the log trace_id field, and is
// back-filled into the request body's TraceId attribute when empty (to
// correlate with upstream GDS echoes).
func NewID() string {
	b := make([]byte, 16)
	if _, err := rand.Read(b); err != nil {
		// Extremely unlikely; a fixed fallback string still suffices for
		// correlation.
		return "fallback"
	}
	// Set the UUID v4 version (4) and variant (10xx) bits per the RFC 4122
	// display form.
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// WithTraceID stores the trace ID in the context and returns the new context.
func WithTraceID(ctx context.Context, id string) context.Context {
	return context.WithValue(ctx, traceIDKey, id)
}

// ID returns the trace ID from the context, or an empty string if absent.
func ID(ctx context.Context) string {
	if ctx == nil {
		return ""
	}
	if v, ok := ctx.Value(traceIDKey).(string); ok {
		return v
	}
	return ""
}

// Ensure guarantees the context carries a trace ID: if one already exists it
// returns the original context and ID; otherwise it generates a new ID,
// stores it and returns the updated context. Calling it uniformly at service
// entry points keeps trace_id present along the whole chain.
func Ensure(ctx context.Context) (context.Context, string) {
	if id := ID(ctx); id != "" {
		return ctx, id
	}
	id := NewID()
	return WithTraceID(ctx, id), id
}
